### ISSUE TITLE
Basic Auth filter authenticates OPTIONS requests and breaks CORS

### ISSUE THREAD

**Issue by jamesdh** [davidtinker/grails-cors#12]
When using this plugin along with the Spring Security basic auth filter, CORS breaks down because it seems the auth is getting applied to the OPTIONS requests as well. This causes the options requests to return with a status of 401 which in turn breaks CORS on pretty much any browser. 

It seems fair that the basic auth filter would get applied to all request types. I'm just wondering if there is some way we can override the default filter behavior when used in conjunction with this plugin. I'd be willing to put in the work and submit a PR but am just throwing this out there for ideas before I get started on it!

**Comment by pashtika** [comment]
Hi - christianjunk it looks like RequestMatcher is an deprecated method. Could you please provide the newer one?
Also one can answer on very similar question? http://stackoverflow.com/questions/32725249/cors-filter-issue-for-authentrypoint

**Comment by ceefour** [comment]
Since Spring Security 4.1, this is the proper way to make Spring Security support CORS (also needed in Spring Boot 1.4/1.5):

```
@Configuration
public class SecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
//        http.csrf().disable();
        http.cors();
    }

    @Bean
    public CorsConfigurationSource corsConfigurationSource() {
        final CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(ImmutableList.of("*"));
        configuration.setAllowedMethods(ImmutableList.of("HEAD",
                "GET", "POST", "PUT", "DELETE", "PATCH"));
        final UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }
}
```

Reference: http://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/cors.html

**Comment by ShurikAg** [comment]
> Since Spring Security 4.1, this is the proper way to make Spring Security support CORS (also needed in Spring Boot 1.4/1.5):
> 
> ```
> @Configuration
> public class SecurityConfig extends WebSecurityConfigurerAdapter {
>     @Override
>     protected void configure(HttpSecurity http) throws Exception {
> //        http.csrf().disable();
>         http.cors();
>     }
> 
>     @Bean
>     public CorsConfigurationSource corsConfigurationSource() {
>         final CorsConfiguration configuration = new CorsConfiguration();
>         configuration.setAllowedOrigins(ImmutableList.of("*"));
>         configuration.setAllowedMethods(ImmutableList.of("HEAD",
>                 "GET", "POST", "PUT", "DELETE", "PATCH"));
>         final UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
>         source.registerCorsConfiguration("/**", configuration);
>         return source;
>     }
> }
> ```
> 
> Reference: http://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/cors.html

I know it's been a while. In grails 5, how do I make this configuration even being loaded. It seems like it is not loaded for me.
Do I need to map it somehow?
