### ISSUE TITLE
Plugin Inaccessible

### ISSUE THREAD

**Issue by hart404** [davidtinker/grails-cors#33]
When I include the following in my BuildConfig.groovy, it cannot be resolved
		runtime ":cors:1.1.6"
The error I get is:

		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: org.grails.plugins#cors;1.1.6: not found
		::::::::::::::::::::::::::::::::::::::::::::::
Not sure what's going on. Here is the repositories section of the BuildConfig.groovy:
	repositories {
		grailsPlugins()
		grailsHome()
		grailsCentral()

		// uncomment the below to enable remote dependency resolution
		// from public Maven repositories
		mavenLocal()
		mavenCentral()
		mavenRepo "http://snapshots.repository.codehaus.org"
		mavenRepo "http://repository.codehaus.org"
		mavenRepo "http://download.java.net/maven/2/"
		mavenRepo "http://repository.jboss.com/maven2/"
		mavenRepo "http://repo.springsource.org/milestone"
		mavenRepo "http://mavenrepo.google-api-java-client.googlecode.com/hg"
	}

**Comment by davidtinker** [comment]
Hmm. Could you post your "plugins" section from BuildConfig? There could be
something wrong or this could be a temp network issue.

On Mon, Mar 2, 2015 at 1:11 AM, Phil Hartley <notifications@github.com>
wrote:

> When I include the following in my BuildConfig.groovy, it cannot be
> resolved
> runtime ":cors:1.1.6"
> The error I get is:
>
>     ::::::::::::::::::::::::::::::::::::::::::::::
>     ::          UNRESOLVED DEPENDENCIES         ::
>     ::::::::::::::::::::::::::::::::::::::::::::::
>     :: org.grails.plugins#cors;1.1.6: not found
>     ::::::::::::::::::::::::::::::::::::::::::::::
>
> Not sure what's going on. Here is the repositories section of the
> BuildConfig.groovy:
> repositories {
> grailsPlugins()
> grailsHome()
> grailsCentral()
>
>     // uncomment the below to enable remote dependency resolution
>     // from public Maven repositories
>     mavenLocal()
>     mavenCentral()
>     mavenRepo "http://snapshots.repository.codehaus.org"
>     mavenRepo "http://repository.codehaus.org"
>     mavenRepo "http://download.java.net/maven/2/"
>     mavenRepo "http://repository.jboss.com/maven2/"
>     mavenRepo "http://repo.springsource.org/milestone"
>     mavenRepo "http://mavenrepo.google-api-java-client.googlecode.com/hg"
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidtinker/grails-cors/issues/33>.
>



-- 
http://qdb.io/ Persistent Message Queues With Replay and #RabbitMQ
Integration

**Comment by hart404** [comment]
Here's the plugins section of BuildConfig.groovy without the reference to the CORS plugin. I inserted the line

runtime ":cors:1.1.6"

after the greenmail plugin reference. I have been having this problem for a week so I don't think it's a temporary network issue (which was my first thought). Thanks for taking a look!

	plugins {
build ":tomcat:7.0.47"
// build ':release:2.2.1'
// compile ':app-info-hibernate:0.2'
compile ":scaffolding:2.0.1"
runtime ":hibernate:3.6.10.4"
runtime ":jquery:1.10.2"
runtime ":resources:1.2.1"
compile ":jquery-ui:1.8.24"
compile ":spring-security-core:1.2.7.3"
compile ":spring-security-ui:0.2"
compile ":famfamfam:1.0.1"
compile ':mail:1.0.1', {
excludes "spring-test"
}
compile ":ckeditor:3.6.3.0"
compile ":csv:0.3.1"
// runtime ":database-migration:1.3.y"
compile ":richui:0.8"
compile ":google-analytics:2.0"
compile ":searchable:0.6.9"
compile ":joda-time:1.5"
compile ":authorize-net:0.12"
test ":greenmail:1.3.4"
}

I got around the issue by downloading the source and pointing the BuildConfig to that.

**Comment by hart404** [comment]
Sorry, did not mean to close the issue

**Comment by vahidhedayati** [comment]
and what happens if you add 
```
mavenRepo "https://repo.grails.org/grails/plugins"
```

Does it work then ?

**Comment by analytik** [comment]
I have the same problem, using Grails 2.4.4. I'm using Ivy instead of Maven.
(Also I'm completely new to Grails, so this might be something simple I'm missing.)

**Comment by analytik** [comment]
Also, maybe I should mention that that was in Ubuntu 14.10 x64. When I tried it today from Windows 8.1 x64 in IntelliJ IDEA 14, it worked on the first try (without any changes in the project). 

In Linux, I still get

```
| Error Resolve error obtaining dependencies: Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.grails.plugins:cors:1.1.6
```

So maybe the problem is in Grails 2.4.4 itself, or in my setup? I've installed it using gvm, without doing anything unusual, and then just ran `grails create-app` to create a hello world project, nothing else.

**Comment by hart404** [comment]
vahidhedayati when I include that repository it resolves the cors plugin. But I don't understand. What does grailsPlugins() in the BuildConfig do if not resolve to the URL you specified?
