### ISSUE TITLE
old prefix grails.plugins.springsecurity

### ISSUE THREAD

**Issue by jagedn** [davidtinker/grails-cors#34]
spring-security-core 2.0 use now grails.plugin.springsecurity as configuration settings meanwhile CorsGrailsPlugin at doWithSpring try to use grails.plugins.security.

"Your security configuration settings use the old prefix 'grails.plugins.springsecurity' but must now use 'grails.plugin.springsecurity' "

**Comment by davidtinker** [comment]
Fixed in 1.1.7.
