### ISSUE TITLE
Minor clarification for Grails 3 users

### ISSUE THREAD

**Issue by rserranon** [davidtinker/grails-cors#38]
Great tool David!

Can you explain in more detail in your readme.md file how to create the servlet filter, where it should be palced, what else needs to be configured?

Thanks

Roberto

**Comment by davidtinker** [comment]
I added a couple of clarifications .. have a look at 974b261

**Comment by rserranon** [comment]
Thx David,

I commented your commit but perhaps is better to have the comment here in the issue, so I post it gain here.

I made the folowing imports, will be good to iclude them in the example, Grails users not always are experienced in Java ;)

```
import java.io.IOException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import org.springframework.web.filter.OncePerRequestFilter;
```

I had to comment:
`@Priority(Integer.MIN_VALUE) `
to be able to compile, I dind't know how to make grails understand the annotation.

Still not working, I´m  getting this error on Chrome Browser:
```
Fetch API cannot load http://rsn.com:8080/entry/index.json.
Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers.
```

and in Mozilla:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://rsn.com:8080/entry/index.json. 
This can be fixed by moving the resource to the same domain or enabling CORS.
```

**Comment by rserranon** [comment]
David, 

I managed to make it work, I had a worg header configured on my client Aurelia Js app. 

I´t is working like a charm!

Thanks

**Comment by davidtinker** [comment]
Cool!
